spring:
  datasource:
    url: jdbc:h2:mem:fda_and_issues;
    driver-class-name: org.h2.Driver
    username: root
    data-password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /api/docs.html


